# language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t silviog1990/production-grade-workflow-exercise -f Dockerfile.dev .

script:
  - docker run -e CI=true silviog1990/production-grade-workflow-exercise npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "production-grade-workflow-exercise"
  env: "ProductionGradeWorkflowExercise-env"
  bucket_name: "elasticbeanstalk-eu-west-1-621061859935"
  bucket_path: "production-grade-workflow-exercise"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY